# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1cfc7d7dc2dd72b1401d00a181aa26c7c706e4600dbdc95e33ab3132ee42713ceae1732a72d06c89e4116abb79c41b446d524cbdbc9e4497a87518b42ee9d67a

test:
  secret_key_base: 018cafffd413d96e507e4a411aeca181118b6a492f84e283062e82bdf8a82361dc2a68ec7bf39e4f076c3021ea96121a69722af1ab9f329f43c665b9e1130b47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
